#!/usr/bin/env bash

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

for dir in ./*/
do
	pushd $dir
	BR=$(git branch --show-current)
	STATUS=$(test -z "$(git status --porcelain)" && echo clean || echo dirty)
	echo -e $dir '\t' $BR '\t' $STATUS
	popd
done
